dist: xenial

language: node_js

node_js:
  - "8"

stages:
  - lint
  - deploy

jobs:
  include:
    - stage: lint
      name: EditorConfig Syntax Verification
      install:
        - npm install -g eclint
        - eclint --version
      script: eclint check
    - stage: lint
      name: Shell Script Syntax Verification
      script: make sh/lint
    - stage: lint
      name: JSON Lint/Format Verification
      script: make json/lint
    - stage: lint
      name: YAML Lint/Format Verification
      install:
        - pip install -r .requirements/yamllint.txt
        - yamllint --version
      language: python
      script:
        - make yaml/lint
    - stage: lint
      name: CFN Lint/Format Verification
      install:
        - pip install -r .requirements/cfn-lint.txt
        - cfn-lint --version
      language: python
      script:
        - make cfn/lint
    - stage: lint
      name: Terraform Lint/Format Verification
      install:
        - make terraform/install
      script:
        - make terraform/lint
    - stage: lint
      name: Terraform Docs Format Verification
      install:
        - make terraform/install
        - make terraform-docs/install
      script:
        - make docs/lint
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-remote-access
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-remote-access v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-remote-access/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: g1iqHy3SKRmzl1utDwEnVQq5sMyM0F0+p7ogEaO6BVkIXUGcDAsfffw0WSBd2UT6nhrPGtOVtvPQckwpuhBiM2Tk71I3LgfiGsMpCTflLXTN6tGFH0qefjl3hgADnhlui7fjgGvwyKkg8DlBgSEYYpEslUtkG9+rjnkPS0nN0fUU4UDek340Juegyj32hI1PCZRoSgv2iQQdEFsABcgMpNTjZMzOL3+lcBhhdKFxNJTVJ6bscMYX5t90JmDJ4ZfsoyIPHKgGvwX+TDfwMKF7FLDw8F6mwqPqF3+CwNMmLD11aoK6dL3iPEAxn4ofT1Dtj1LUdWDSa/qNHdzRYUnwZPLiqv0D/HqGEyYa7BhyQUdroYXeKRB/KV5ni2Lu4gwiNSHCYc9ykze/JoEJgN1rS3eBblOXmtaslHtigMGgmfk3tUGwe7ht6xnVgw5uBv8TC982DH0Vwj6/I5J2ywulfZJnPqx1edTJla0XJ4Kc3NnwmLvVuYFf88ZrRXOZAYdo+T+RRXLNsCqHE5DY56R/eZXoRsB4goRCK1ZSxUi15HbDGqp/2D3phAQt4aSNElXbAk+/jTqSLWFjCEKLHEkL6stIjkzU0WdQy/937v00CRr2OAzxswvWXhWRu9fdG01YWRocRb7aCJWiO4qPyg3Dbt2Fiah25pKYoMA2N3G+V60=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-remote-access
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
