version: 0.2

phases:
  pre_build:
    commands:
      - "apk update"
      - "apk add python3"
      - "apk add python3-dev"
      - "apk add py3-setuptools"
      - "pip3 install awscli"
      - "terraform --version"
      - "START_DIR=$(pwd)"
      - "cd $START_DIR/modules/rdcb && terraform init -no-color -input=false"
      - "terraform plan -no-color -out=tfplan -input=false"
      - "export TF_VAR_StackName=rdcb-ci-test"
      - "cd $START_DIR/modules/rdgw && terraform init -no-color -input=false"
      - "export TF_VAR_StackName=rdgw-ci-test"
      - "terraform plan -no-color -out=tfplan -input=false"
  build:
    commands:
      - "cd $START_DIR/modules/rdcb"
      - "export TF_VAR_StackName=rdcb-ci-test"
      - "terraform apply -no-color -input=false tfplan"
      - "cd $START_DIR/modules/rdgw"
      - "export TF_VAR_StackName=rdgw-ci-test"
      - "terraform apply -no-color -input=false tfplan"
  post_build:
    commands:
      - "export TF_VAR_StackName=rdcb-ci-test"
      - if [ "${DESTROY_AFTER_TEST}" = "true" ]; then cd $START_DIR/modules/rdcb && terraform destroy -no-color -input=false -force; fi
      - "export TF_VAR_StackName=rdgw-ci-test"
      - if [ "${DESTROY_AFTER_TEST}" = "true" ]; then cd $START_DIR/modules/rdgw && terraform destroy -no-color -input=false -force; fi
artifacts:
  files:
    - modules/rdcb/terraform.tfstate
    - modules/rdcb/terraform.log
    - modules/rdcb/terraform_output.log
  discard-paths: yes
