version: 0.2

phases:
  pre_build:
    commands:
      - "terraform --version"
      - "cd modules/rdcb && terraform init -no-color -input=false"
      - "terraform plan -no-color -out=tfplan -input=false"
      - "echo StackName var is $TF_ENV_StackName"
  build:
    commands:

