version: 0.2

phases:
  pre-build:
    commands:
      - "terraform --version"
      - "cd modules/rdcb && terraform init -no-color -input=false"
      - "terraform plan -no-color -out=tfplan -input=false"
  build:
    commands:

