version: 1

update_configs:

  - package_manager: "terraform"
    directory: "/modules/guac"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/modules/rdcb"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/modules/rdgw"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/modules/rdsh"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/example_testcase"
    update_schedule: "daily"

  - package_manager: "go:modules"
    directory: "/tests"
    update_schedule: "daily"

  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
